## netlify.toml

[build]
  publish = "out"
  command = "next build && next export"

[[plugins]]
	package = "netlify-plugin-next-dynamic"

[[plugins]]
	package = "netlify-plugin-cache-nextjs"

[[plugins]]
	package = "netlify-plugin-image-optim"